name: Generate Achievement Index

on:
  push:
    paths:
      - "docs/achievements/**"
      - ".github/workflows/generate-achievement-index.yml"

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate index.json
        run: |
          mkdir -p docs/achievements
          ls -tp docs/achievements | grep -v '/$' | grep -v index.json | head -n 100 | jq -R -s -c 'split(\"\\n\") | map(select(length > 0))' > docs/achievements/index.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/achievements/index.json
          git diff --cached --quiet || git commit -m "🔄 Update achievement index"
          git push --force
